// Tiny DOCX builder. We only need a minimal subset (paragraphs + headings),
// so rather than pull in the heavy `docx` npm package we hand-construct an
// Office Open XML zip. This keeps the bundle tiny and works offline.
//
// Outputs a downloadable .docx for a tender checklist. Browser-only.

import JSZipShim from './jszipShim.js';

function escapeXml(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function paragraph(text, { heading = false, bold = false } = {}) {
  const styleId = heading ? 'Heading1' : 'Normal';
  const runProps = bold ? '<w:rPr><w:b/></w:rPr>' : '';
  return `<w:p>
    <w:pPr><w:pStyle w:val="${styleId}"/></w:pPr>
    <w:r>${runProps}<w:t xml:space="preserve">${escapeXml(text)}</w:t></w:r>
  </w:p>`;
}

function checklistItem(text) {
  return `<w:p>
    <w:pPr>
      <w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr>
      <w:pStyle w:val="ListParagraph"/>
    </w:pPr>
    <w:r><w:t xml:space="preserve">${escapeXml(text)}</w:t></w:r>
  </w:p>`;
}

const CONTENT_TYPES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
  <Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/>
</Types>`;

const ROOT_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`;

const DOC_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/>
</Relationships>`;

const STYLES = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:style w:type="paragraph" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="22"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="Heading 1"/><w:basedOn w:val="Normal"/><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:b/><w:sz w:val="36"/><w:color w:val="1B2C45"/></w:rPr><w:pPr><w:spacing w:before="240" w:after="120"/></w:pPr></w:style>
  <w:style w:type="paragraph" w:styleId="ListParagraph"><w:name w:val="List Paragraph"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:after="80"/></w:pPr></w:style>
</w:styles>`;

const NUMBERING = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:numbering xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:abstractNum w:abstractNumId="0">
    <w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="bullet"/><w:lvlText w:val="•"/><w:lvlJc w:val="left"/><w:pPr><w:ind w:left="720" w:hanging="360"/></w:pPr></w:lvl>
  </w:abstractNum>
  <w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num>
</w:numbering>`;

function buildDocumentXml(tender, items) {
  const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const parts = [];
  parts.push(paragraph('Tender Requirements Checklist', { heading: true }));
  parts.push(paragraph(tender.title || 'Untitled tender', { bold: true }));
  parts.push(paragraph(`Issuer: ${tender.issuer || 'Not specified'}`));
  if (tender.refNo) parts.push(paragraph(`Reference: ${tender.refNo}`));
  if (tender.closes) parts.push(paragraph(`Closes: ${new Date(tender.closes).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`));
  parts.push(paragraph(`Generated by TenderFlow on ${today}`));
  parts.push(paragraph(''));
  parts.push(paragraph('Mandatory documents and requirements:', { bold: true }));
  for (const item of items) {
    parts.push(checklistItem(item.text || ''));
  }
  parts.push(paragraph(''));
  parts.push(paragraph('Use this checklist as a starting point. Always cross-check against the original tender document, which may include additional requirements.'));

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    ${parts.join('\n    ')}
    <w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>
  </w:body>
</w:document>`;
}

export async function downloadChecklistDocx(tender, items) {
  const zip = new JSZipShim();
  zip.file('[Content_Types].xml', CONTENT_TYPES);
  zip.folder('_rels').file('.rels', ROOT_RELS);
  const word = zip.folder('word');
  word.file('document.xml', buildDocumentXml(tender, items));
  word.file('styles.xml', STYLES);
  word.file('numbering.xml', NUMBERING);
  word.folder('_rels').file('document.xml.rels', DOC_RELS);

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${(tender.refNo || tender.id || 'tender').replace(/[^A-Za-z0-9_.-]/g, '_')}-checklist.docx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
